name: Alpha Release

on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - '.github/workflows/alpha-release.yml'

jobs:
  android-release:
    name: Build Android Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.CAMPFIRE_KEYSTORE }}
        run: |
          echo $ENCODED_KEYSTORE | base64 -di > app/signing/campfire.keystore

      - name: Download Service Accounts
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          APP_DISTRIBUTION_JSON: ${{ secrets.APP_DISTRIBUTION_SERVICE_ACCOUNT }}
        run: |
          echo $GOOGLE_SERVICES_JSON > app/android/google-services.json
          echo $APP_DISTRIBUTION_JSON > app/android/campfire-app-distribution-service-account.json

      - name: Assemble Alpha Release APK
        run: ./gradlew :app:android:assembleAlphaRelease
        env:
          ORG_GRADLE_PROJECT_CAMPFIRE_KEYSTORE_PWD: ${{ secrets.CAMPFIRE_KEYSTORE_PWD }}
          ORG_GRADLE_PROJECT_CAMPFIRE_KEY_PWD: ${{ secrets.CAMPFIRE_KEY_PWD }}
          ORG_GRADLE_PROJECT_mixpanel_token: ${{ secrets.MIXPANEL_TOKEN }}
          ORG_GRADLE_PROJECT_CAMPFIRE_VERSIONCODE: ${{ github.run_number }}
          CI: true

      - name: Create Release Notes
        run: |
          ./campfire changelog --version Unreleased > app/android/release-notes.txt
          echo " "
          cat app/android/release-notes.txt

      - name: Firebase App Distribution
        run: |
          ./gradlew :app:android:appDistributionUploadAlphaRelease \
            --serviceCredentialsFile="app/android/campfire-app-distribution-service-account.json" \
            --releaseNotesFile="app/android/release-notes.txt"

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: android-build-outputs
          path: app/android/build/outputs
