name: Baseline profile generation

on:
  # Every Sunday at 00:43
  schedule:
    - cron: '43 0 * * 0'
  workflow_dispatch:
  pull_request:
    paths:
      - 'app/baselineprofile/**'
      - '.github/workflows/baseline-profile.yml'

jobs:
  baseline-profile:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v5
        with:
          # We need to use a Personal Access Token from an admin to be able to commit to main,
          # as it is a protected branch.
          # https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-fine-grained-personal-access-token
          token: ${{ secrets.CAMPFIRE_BOT_PAT }}

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Accept Android SDK license
        run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Download Service Accounts
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON > app/android/google-services.json

      - name: Build app and benchmark
        run: ./gradlew assembleNonMinifiedRelease
        env:
          ORG_GRADLE_PROJECT_CAMPFIRE_SERVER_URL: ${{ secrets.SERVER_URL }}
          ORG_GRADLE_PROJECT_CAMPFIRE_USERNAME: ${{ secrets.TEST_USER_NAME }}
          ORG_GRADLE_PROJECT_CAMPFIRE_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-36

      - name: Generate Baseline Profiles
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 36
          target: google_apis
          arch: x86_64
          profile: pixel_7
          ram-size: 4096M
          disk-size: 6000M
          heap-size: 600M
          script: |
            ./gradlew generateBaselineProfile \
              -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile
        env:
          ORG_GRADLE_PROJECT_CAMPFIRE_SERVER_URL: ${{ secrets.SERVER_URL }}
          ORG_GRADLE_PROJECT_CAMPFIRE_USERNAME: ${{ secrets.TEST_USER_NAME }}
          ORG_GRADLE_PROJECT_CAMPFIRE_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
#
#      - name: Generate Baseline Profiles
#        run: |
#          ./gradlew generateBaselineProfile \
#            -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" \
#            -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile \
#            -Pandroid.experimental.testOptions.managedDevices.setupTimeoutMinutes=10 \
#            --no-configuration-cache
#        env:
#          ORG_GRADLE_PROJECT_CAMPFIRE_SERVER_URL: ${{ secrets.SERVER_URL }}
#          ORG_GRADLE_PROJECT_CAMPFIRE_USERNAME: ${{ secrets.TEST_USER_NAME }}
#          ORG_GRADLE_PROJECT_CAMPFIRE_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

      # If we're on main branch, copy over the baseline profile and
      # commit it to the repository (if changed)
      - name: Commit baseline profile into main
        if: github.ref == 'refs/heads/main'
        run: |
          # If the baseline profile has changed, commit it
          if [[ $(git diff --stat app/android/src) != '' ]]; then
            git config user.name Rotom-Bot
            git config user.email veedubusc+deckbox@gmail.com
            git add app/android/src
            git commit -m "Update app baseline profile"
            git pull --rebase
            git push
          fi

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: reports
          path: |
            **/build/reports/*
