name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  danger-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    name: "danger-pr"
    container:
      image: docker://ghcr.io/r0adkll/danger-kotlin:2.0.8
    steps:
      - uses: actions/checkout@v6
      - name: Run Danger
        run: danger-kotlin ci --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.CAMPFIRE_BOT_PAT }}
          ref: ${{ github.head_ref }}

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Check convention plugins code style with Spotless
        if: always()
        run: ./gradlew -p gradle/build-logic spotlessApply

      - name: Check code style with Spotless
        if: always()
        run: ./gradlew spotlessApply

      - name: Push changes to PR if exist
        env:
          IS_PULL_REQUEST: ${{ github.event_name == 'pull_request' }}
        run: |
          # If there are any changes from running spotlessApply, push to PR
          if [[ $(git diff --stat .) != '' ]]; then
            echo "Changes detectedâ€¦"
            # We only want to push changes to the branch if we are on a pull request
            if [[ "$IS_PULL_REQUEST" == "true" ]]; then
              echo "Pull Request, pushing changes to branch"
              git config user.name Rotom-Bot
              git config user.email veedubusc+deckbox@gmail.com
              git commit -am "Automated Code Style Updates"
              git push
            fi

            # If there are changes, always fail
            exit 1
          fi

  code-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Download Google Services JSON
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON > app/android/google-services.json

      - name: Check skip-coverage label is added
        id: label-check
        run: |
          if gh api --jq '.labels.[].name' /repos/r0adkll/Campfire/pulls/${{ github.event.number }} | grep -q "skip-coverage"
          then
            echo "SKIP_COVERAGE=true" >> "$GITHUB_OUTPUT"
          else
            echo "SKIP_COVERAGE=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check label output
        run: echo "${{ steps.label-check.outputs.SKIP_COVERAGE }}"

      - name: Run tests and generate coverage report
        if: ${{ steps.label-check.outputs.SKIP_COVERAGE == 'false' }}
        run: ./gradlew --quiet test allTests koverXmlReport

      - name: Add coverage report to PR
        if: ${{ steps.label-check.outputs.SKIP_COVERAGE == 'false' }}
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/build/reports/kover/report.xml
          title: Code Coverage
          token: ${{ secrets.CAMPFIRE_BOT_PAT }}
          update-comment: true
          min-coverage-overall: 50
          min-coverage-changed-files: 80
          coverage-counter-type: LINE

      - name: Fail if coverage is not met
        if: ${{ steps.label-check.outputs.SKIP_COVERAGE == 'false' }}
        run: |
          if [[ "${{ steps.kover.outputs.coverage-changed-files }}" -lt 50 ]]; then
            exit 1
          fi

  android:
    needs: [code-style]
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Generate build number
        shell: bash
        run: echo "ORG_GRADLE_PROJECT_CAMPFIRE_VERSIONCODE=$(( $GITHUB_RUN_NUMBER + 10000 ))" >> $GITHUB_ENV

      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Download Google Services JSON
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON > app/android/google-services.json

      - name: Build Android App
        run: |
          ./gradlew --quiet :app:android:assembleAlphaRelease

      # FIXME: Disable for now as we need to figure out how to run the danger container from here
      # - name: Danger Lint
      #   if: ${{ github.event_name == 'pull_request' }}
      #   uses: docker://ghcr.io/danger/danger-kotlin:1.3.3
      #   with:
      #     args: --failOnErrors --no-publish-check
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK
        id: upload_artifact
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: android-alpha-release-apk
          path: app/android/build/outputs/apk/alpha/release/android-alpha-release.apk

      - name: Post Artifact URL to PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            [Android APK](${{ steps.upload_artifact.outputs.artifact-url }}) @ ${{ github.sha }}
          comment-tag: apk_url

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: android-reports
          path: |
            **/build/reports/*

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: android-test-results
          path: |
            **/build/test-results/*

  desktop:
    needs: [code-style]
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build Desktop App
        run: ./gradlew --quiet :app:desktop:packageDistributionForCurrentOS

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: desktop-build-binaries
          path: app/desktop/build/compose/binaries

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: desktop-reports
          path: |
            **/build/reports/*

  ios-test:
    needs: [code-style]
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: iosSimulatorArm64Test
        run: ./gradlew iosSimulatorArm64Test

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: ios-reports
          path: |
            **/build/reports/*

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: ios-test-results
          path: |
            **/build/test-results/*
