name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  danger-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    name: "danger-pr"
    container:
      image: docker://ghcr.io/r0adkll/danger-kotlin:2.0.8
    steps:
      - uses: actions/checkout@v5
      - name: Run Danger
        run: danger-kotlin ci --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code-style:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v5

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v3
        with:
          cache-disabled: true

      - name: Check convention plugins code style with Spotless
        run: ./gradlew -p gradle/build-logic spotlessCheck

      - name: Check code style with Spotless
        run: ./gradlew spotlessCheck

  android:
    needs: [code-style]
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    steps:
      - name: Generate build number
        shell: bash
        run: echo "ORG_GRADLE_PROJECT_CAMPFIRE_VERSIONCODE=$(( $GITHUB_RUN_NUMBER + 10000 ))" >> $GITHUB_ENV

      - uses: actions/checkout@v5

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v3
        with:
          cache-disabled: true

      - name: Download Google Services JSON
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON > app/android/google-services.json

      - name: Build Android App
        run: |
          ./gradlew :app:android:assembleStandardRelease

      # FIXME: Disable for now as we need to figure out how to run the danger container from here
      # - name: Danger Lint
      #   if: ${{ github.event_name == 'pull_request' }}
      #   uses: docker://ghcr.io/danger/danger-kotlin:1.3.3
      #   with:
      #     args: --failOnErrors --no-publish-check
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK
        id: upload_artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-standard-release-apk
          path: app/android/build/outputs/apk/standard/release/android-standard-release.apk

      - name: Post Artifact URL to PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            [Android APK](${{ steps.upload_artifact.outputs.artifact-url }}) @ ${{ github.sha }}
          comment-tag: apk_url

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-reports
          path: |
            **/build/reports/*

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-results
          path: |
            **/build/test-results/*

  desktop:
    needs: [code-style]
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v5

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v3
        with:
          cache-disabled: true

      - name: Build Desktop App
        run: ./gradlew jvmTest :app:desktop:packageDistributionForCurrentOS

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: desktop-build-binaries
          path: app/desktop/build/compose/binaries

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: desktop-reports
          path: |
            **/build/reports/*

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: desktop-test-results
          path: |
            **/build/test-results/*

  ios-test:
    needs: [code-style]
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v5

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v3
        with:
          cache-disabled: true

      - name: iosSimulatorArm64Test
        run: ./gradlew iosSimulatorArm64Test

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-reports
          path: |
            **/build/reports/*

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-test-results
          path: |
            **/build/test-results/*
