name: Release

on:
  release:
    types: [ created ]

jobs:
  android-release:
    name: Build Android Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: gradle

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.CAMPFIRE_KEYSTORE }}
        run: |
          echo $ENCODED_KEYSTORE | base64 -di > app/signing/campfire.keystore

      - name: Download Service Accounts
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          APP_DISTRIBUTION_JSON: ${{ secrets.APP_DISTRIBUTION_SERVICE_ACCOUNT }}
        run: |
          echo $GOOGLE_SERVICES_JSON > app/android/google-services.json
          echo $APP_DISTRIBUTION_JSON > app/android/campfire-app-distribution-service-account.json

      # TODO: Run baseline profile generator

      - name: Assemble Release APK
        run: ./gradlew :app:android:assembleRelease :app:android:bundleRelease
        env:
          ORG_GRADLE_PROJECT_CAMPFIRE_KEYSTORE_PWD: ${{ secrets.CAMPFIRE_KEYSTORE_PWD }}
          ORG_GRADLE_PROJECT_CAMPFIRE_KEY_PWD: ${{ secrets.CAMPFIRE_KEY_PWD }}
          ORG_GRADLE_PROJECT_CAMPFIRE_VERSIONCODE: ${{ github.run_number }}
          ORG_GRADLE_PROJECT_CAMPFIRE_VERSIONNAME: ${{ github.event.release.tag_name }}
          CI: true

      - name: Parse Changelog
        id: changelog
        uses: coditory/changelog-parser@v1

      - name: Firebase App Distribution
        run: |
          ./gradlew :app:android:appDistributionUploadRelease \
            --serviceCredentialsFile="app/android/campfire-app-distribution-service-account.json" \
            --releaseNotes="${{ steps.changelog.outputs.description }}"

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-build-outputs
          path: app/android/build/outputs

      - name: Get release information
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload APK to release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: app/android/build/outputs/apk/release/android-release.apk
          asset_name: campfire-release.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload AAB to release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: app/android/build/outputs/bundle/release/android-release.aab
          asset_name: campfire-release.aab
          asset_content_type: application/octet-stream
