name: Release

on:
  release:
    types: [ created ]

jobs:
  android-release:
    name: Build Android Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.CAMPFIRE_KEYSTORE }}
        run: |
          echo $ENCODED_KEYSTORE | base64 -di > app/signing/campfire.keystore

      - name: Download Service Accounts
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          APP_DISTRIBUTION_JSON: ${{ secrets.APP_DISTRIBUTION_SERVICE_ACCOUNT }}
        run: |
          echo $GOOGLE_SERVICES_JSON > app/android/google-services.json
          echo $APP_DISTRIBUTION_JSON > app/android/campfire-app-distribution-service-account.json

      - name: Assemble Beta Release APK
        run: ./gradlew :app:android:assembleBetaRelease
        env:
          ORG_GRADLE_PROJECT_CAMPFIRE_KEYSTORE_PWD: ${{ secrets.CAMPFIRE_KEYSTORE_PWD }}
          ORG_GRADLE_PROJECT_CAMPFIRE_KEY_PWD: ${{ secrets.CAMPFIRE_KEY_PWD }}
          ORG_GRADLE_PROJECT_mixpanel_token: ${{ secrets.MIXPANEL_TOKEN }}
          ORG_GRADLE_PROJECT_CAMPFIRE_VERSIONCODE: ${{ github.run_number }}
          ORG_GRADLE_PROJECT_CAMPFIRE_VERSIONNAME: ${{ github.event.release.tag_name }}
          CI: true

      - name: Create Release Notes
        run: |
          ./campfire changelog > app/android/release-notes.txt
          echo " "
          cat app/android/release-notes.txt

      - name: Firebase App Distribution
        run: |
          ./gradlew :app:android:appDistributionUploadBetaRelease \
            --serviceCredentialsFile="app/android/campfire-app-distribution-service-account.json" \
            --releaseNotesFile="app/android/release-notes.txt"

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: android-build-outputs
          path: app/android/build/outputs

      - name: Get release information
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload APK to release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: app/android/build/outputs/apk/beta/release/android-beta-release.apk
          asset_name: campfire-beta-release.apk
          asset_content_type: application/vnd.android.package-archive
